export default {
    basePath: 'http://47.97.97.45/xiyou/account.php',
    fileBasePath: 'http://47.97.97.45/xiyou',

    storeId: 1001,


    CONFIG: {
        base_url: "http://47.97.97.45/xiyou",
        index_url: "http://47.97.97.45/xiyou/index.php",
        admin_url: "http://47.97.97.45/xiyou/admin.php",
        index_page: "index.php",
        static_url: "http://47.97.97.45/xiyou/shop/static/src/default"
    },

    SYS_TYPE : 'multi',
    MULTISHOP_ENABLE : 0,
    EVALUATION_ENABLE : 1,
    SAAS_STATUS : 0,
    STORE_ID : 1001,
    VIRTUAL_ENABLE : 0,
    O2O_ENABLE : 1,

    REDPACKET_ENABLE : 0,
    CREDIT_ENABLE : 0,


    CACHE : true,
    CACHE_EXPIRE : 3600 * 1,


URL: {
        "index": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=mobile&typ=json",
        "index_app": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=app&typ=json",
        "center_menu": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=userCenterMenu&typ=json",
        "upload": "http://47.97.97.45/xiyou/index.php?ctl=Media&met=uploadImage&typ=json",
        "upload_config": "http://47.97.97.45/xiyou/index.php?ctl=Media&met=config&typ=json",
        "info": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=info&typ=json",
        "page": "http://47.97.97.45/xiyou/index.php?ctl=Page&met=get&typ=json",
        "mini_page": "http://47.97.97.45/xiyou/index.php?ctl=Page&met=getMiniPage&typ=json",
        "survey": "http://47.97.97.45/xiyou/index.php?ctl=Page&met=doSurvey&typ=json",
        "product": {
            "item": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=item&typ=json",
            "quick": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=quick&typ=json",
            "info": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=info&typ=json",
            "lists": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=lists&typ=json",
            "shipping_district": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=shippingDistrict&typ=json",
            "category": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=category&typ=json",
            "brand": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=brand&typ=json",
            "product_comment": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=comment&typ=json",
            "add_comment_reply": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=addCommentReply&typ=json",
            "comment_helpful": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=commentHelpful&typ=json",
            "faq": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=faq&typ=json",
            "popular": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=productPopular&typ=json",
            "spec": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=getSpec&typ=json"
        },
        "loginInfo": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=getLoginInfo&typ=json",
        "search_filter": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=getSearchFilter&typ=json",
        "district": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=district&typ=json",
        "district_all": "http://47.97.97.45/xiyou/shop/static/src/default/js/city.js",
        "district_id": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=getDistrictByName&typ=json",
        "search_hot_info": "http://47.97.97.45/xiyou/index.php?ctl=Index&met=getSearchInfo&typ=json",
        "connect": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=getConnectInfo&typ=json",
        "login_box": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=index&typ=e",
        "set_pwd": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=setNewPassword&typ=json",
        "login": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=doLogin&typ=json",
        "register": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=doRegister&typ=json",
        "logout": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=logout&typ=json",
        "check_mobile_or_email": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=checkMobileOrEmail&typ=json",
        "find_pwd_s2": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=findpwdStepTwo&typ=e&step=2",
        "find_pwd_s3": "http://47.97.97.45/xiyou/account.php?ctl=Login&met=findpwdStepThree&typ=e&step=3",
        "delivery_info": "http://47.97.97.45/xiyou/shop/api/delivery.php",
        "account": {
            "certificate": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=certification&typ=e",
            "get_mobile_info": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=index&typ=json",
            "check_mobile_code": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=checkMobile&typ=json",
            "get_mobile_checkcode": "http://47.97.97.45/xiyou/account.php?ctl=VerifyCode&met=mobile&typ=json",
            "check_security_change": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=checkSecurityChange&typ=json",
            "reset_password": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=resetPassword&typ=json",
            "bind_mobile": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=bindMobile&typ=json",
            "commit_certificate": "http://47.97.97.45/xiyou/account.php?ctl=User_Security&met=saveCertificate&typ=json",
            "edit_user_info": "http://47.97.97.45/xiyou/account.php?ctl=User_Account&met=edit&typ=json",
        },
        "wx": {
            "share": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=share&typ=e",
            "config": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=wxConfig&typ=e",
            "pay_config": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=wxPayConfig&typ=json",
            "mplogin": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=login&typ=e&flag=mp",
            "openlogin": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=login&typ=e&flag=open",
            "applogin": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=jscode2session&typ=json&flag=app",
            "getQRCode": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=getQRCode&typ=json&flag=app",
            "getMiniAppQRCode": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=getMiniAppQRCode&typ=json&flag=app",
            "getMiniAppQRCodeUnlimit": "http://47.97.97.45/xiyou/account.php?ctl=Connect_Weixin&met=getMiniAppQRCodeUnlimit&typ=json&flag=app",
        },
        "store": {
            "get": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=get&typ=json",
            "add": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=add&typ=json",
            "credit": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=credit&typ=json",
            "info": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=info&typ=json",
            "contents": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=contents&typ=json",
            "index_diy": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=indexDiy&typ=json",
            "profile": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=profile&typ=json",
            "menu": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=menu&typ=json",
            "lists": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=lists&typ=json",
            "listsChain": "http://47.97.97.45/xiyou/index.php?ctl=Chain&met=lists&typ=json",
            "getNearChain": "http://47.97.97.45/xiyou/index.php?ctl=Chain&met=getNearChain&typ=json",

            "near": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=lists&typ=json",
            "category": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=category&typ=json",
            "activity": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=activity&typ=json",
            "product": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=lists&typ=json",
            "item": "http://47.97.97.45/xiyou/index.php?ctl=Product&met=lists&typ=json",
            "product_category": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=productCategory&typ=json",
            "product_popular": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=productPopular&typ=json",
            "lists_store_grade": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=listsStoreGrade&typ=json",
            "lists_store_category": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=listsStoreCategory&typ=json",
            "commit_payment_voucher": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=paymentVoucher&typ=json",
            "config": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=getConfig&typ=json",
            "survey": "http://47.97.97.45/xiyou/index.php?ctl=Store&met=doSurvey&typ=json",

        },
        "point": {
            "voucher": "http://47.97.97.45/xiyou/index.php?ctl=Point&met=voucher&typ=json",
        },
        "verify": {
            "image": "http://47.97.97.45/xiyou/account.php?ctl=VerifyCode&met=image&typ=json",
            "mobile": "http://47.97.97.45/xiyou/account.php?ctl=VerifyCode&met=mobile&typ=json",
            "email": "http://47.97.97.45/xiyou/account.php?ctl=VerifyCode&met=email&typ=json"
        },
        "cart": {
            "add": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=add&typ=json",
            "remove": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=remove&typ=json",
            "edit": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=edit&typ=json",
            "lists": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=lists&typ=json",
            "listsMini": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=listsMini&typ=json",
            "quantity": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=editQuantity&typ=json",
            "cookie": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=getCookieCart&typ=json",
            "index": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=index&typ=json",
            "sel": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=sel&typ=json",
            "checkout": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=checkout&typ=json",
            "checkDelivery": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=checkDelivery&typ=json",
            "order": "http://47.97.97.45/xiyou/index.php?ctl=Cart&met=order&typ=e"
        },
        "seller": {
            "store": "http://47.97.97.45/xiyou/admin.php?mdu=seller&ctl=Store_Base&met=get&typ=json",
            "product": "http://47.97.97.45/xiyou/admin.php?mdu=seller&ctl=Product&met=lists&typ=json",
            "item": "http://47.97.97.45/xiyou/admin.php?mdu=seller&ctl=Product&met=lists&typ=json"
        },
        "cms": {
            "lists": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=lists&typ=json",
            "category": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=category&typ=json",
            "get": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=get&typ=json",
            "add_article_comment": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=addComment&typ=json",
            "add_article_comment_reply": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=addCommentReply&typ=json",
            "get_related_article": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=getRelatedArticle&typ=json",
            "comment_helpful": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=commentHelpful&typ=json",
            "remove_comment_helpful": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=removeCommentHelpful&typ=json",
            "comment_reply_helpful": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=commentReplyHelpful&typ=json",
            "remove_comment_reply_helpful": "http://47.97.97.45/xiyou/index.php?mdu=cms&ctl=Article&met=removeCommentReplyHelpful&typ=json"
        },
        "user": {
            "overview": "http://47.97.97.45/xiyou/index.php?ctl=User_Account&met=overview&typ=json",
            "cart_count": "http://47.97.97.45/xiyou/index.php?ctl=User_Account&met=getCartNum&typ=json",
            "msg_count": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Message&met=getMsgCount&typ=json",
            "msg_config": "http://47.97.97.45/xiyou/account.php?ctl=Index&met=getConfig&typ=json",
            "msg_lists": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Message&met=lists&typ=json",
            "msg_user_lists": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Message&met=getMsgUser&typ=json",
            "msg_add": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Message&met=add&typ=json",
            "msg_remove": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Message&met=remove&typ=json",
            "msg_remove_user": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Message&met=removeUserMsg&typ=json",
            "lists_base_level": "http://47.97.97.45/xiyou/account.php?ctl=Index&met=listBaseUserLevel&typ=json",
            "friend_info_lists": "http://47.97.97.45/xiyou/account.php?mdu=sns&ctl=User_Friend&met=getFriendsInfo&typ=json",
            "more_comment": "http://47.97.97.45/xiyou/index.php?ctl=User_Comment&met=loadMoreComment&typ=json",
            "add_product_comment": "http://47.97.97.45/xiyou/index.php?ctl=User_Comment&met=add&typ=json",
            "add_order_comment": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=addOrderComment&typ=json",
            "ask_helpful": "http://47.97.97.45/xiyou/index.php?ctl=User_Ask&met=hasHelpful&typ=json",
            "ask_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Ask&met=add&typ=json",
            "edit": "http://47.97.97.45/xiyou/index.php?ctl=User_Account&met=edit&typ=json",
            "lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Account&met=lists&typ=json",
            "points": "http://47.97.97.45/xiyou/index.php?ctl=User_Resource&met=pointsHistory&typ=json",
            "signState": "http://47.97.97.45/xiyou/index.php?ctl=User_Resource&met=signState&typ=json",
            "listsExp": "http://47.97.97.45/xiyou/index.php?ctl=User_Resource&met=listsExp&typ=json",
            "listsExpRule": "http://47.97.97.45/xiyou/index.php?ctl=User_Resource&met=listsExpRule&typ=json",
            "resource": "http://47.97.97.45/xiyou/index.php?ctl=User_Resource&met=resource&typ=json",
            "signIn": "http://47.97.97.45/xiyou/index.php?ctl=User_Resource&met=signIn&typ=json",
            "voucherList": "http://47.97.97.45/xiyou/index.php?ctl=User_Voucher&met=lists&typ=json",
            "lists_voucher_product": "http://47.97.97.45/xiyou/index.php?ctl=User_Voucher&met=listsVoucherProduct&typ=json",
            "voucherNum": "http://47.97.97.45/xiyou/index.php?ctl=User_Voucher&met=getVoucherNum&typ=json",
            "eachVoucherNum": "http://47.97.97.45/xiyou/index.php?ctl=User_Voucher&met=getEachVoucherNum&typ=json",
            "voucher_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Voucher&met=add&typ=json",
            "voucher_used": "http://47.97.97.45/xiyou/index.php?ctl=User_Voucher&met=checkVoucher&typ=json",
            "return_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Return&met=lists&typ=json",
            "return_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Return&met=add&typ=json",
            "return_add_one": "http://47.97.97.45/xiyou/index.php?ctl=User_Return&met=addItem&typ=json",
            "return_item": "http://47.97.97.45/xiyou/index.php?ctl=User_Return&met=returnItem&typ=json",
            "return_cancel": "http://47.97.97.45/xiyou/index.php?ctl=User_Return&met=cancel&typ=json",
            "return_confirm_refund": "http://47.97.97.45/xiyou/index.php?ctl=User_Return&met=confirmRefund&typ=json",
            "invoice_type": "http://47.97.97.45/xiyou/index.php?ctl=User_Invoice&met=type&typ=json",
            "invoice_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Invoice&met=lists&typ=json",
            "invoice_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Invoice&met=add&typ=json",
            "invoice_get": "http://47.97.97.45/xiyou/index.php?ctl=User_Invoice&met=get&typ=json",
            "invoice_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_Invoice&met=remove&typ=json",
            "order_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=add&typ=json",
            "order_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=lists&typ=json",
            "order_cancel": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=cancel&typ=json",
            "order_receive": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=receive&typ=json",
            "order_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=remove&typ=json",
            "order_detail": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=detail&typ=json",
            "order_delivery": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=delivery&typ=json",
            "order_index": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=index&typ=e",
            "order_comment_manage": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=storeCommentManage&typ=json",
            "order_comment_with_content": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=storeEvaluationWithContent&typ=json",
            "order_comment_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Order&met=addOrderComment&typ=json",
            "wish_store_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=lists&typ=json&action=store",
            "wish_item_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=lists&typ=json&action=item",
            "wish_brand_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=lists&typ=json&action=brand",
            "wish_store_get": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=get&typ=json&action=store",
            "wish_item_get": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=get&typ=json&action=item",
            "wish_brand_get": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=get&typ=json&action=brand",
            "wish_store_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=remove&typ=json&action=store",
            "wish_item_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=remove&typ=json&action=item",
            "wish_brand_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=remove&typ=json&action=brand",
            "wish_store_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=add&typ=json&action=store",
            "wish_item_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=add&typ=json&action=item",
            "wish_brand_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=add&typ=json&action=brand",
            "browser_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=browser&typ=json&action=item",
            "browser_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_Favorites&met=removeBrowser&typ=json&action=item",
            "feedback_add": "http://47.97.97.45/xiyou/index.php?ctl=User_Feedback&met=add&typ=json",
            "address_add": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=save&typ=json",
            "check_wechat_address": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=checkWeChatAddress&typ=json",
            "address_get": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=get&typ=json",
            "address_edit": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=save&typ=json",
            "address_lists": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=lists&typ=json",
            "address_remove": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=remove&typ=json",
            "address_manage": "http://47.97.97.45/xiyou/index.php?ctl=User_DeliveryAddress&met=manage&typ=e",
            "joinIn": "http://47.97.97.45/xiyou/index.php?ctl=Join&met=step&typ=e",

            "listsLottery": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=getLottery&typ=json",
            "doLottery": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=doLottery&typ=json",
            "listsLotteryHistory": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=listsLotteryHistory&typ=json",
            "getLotteryHistory": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=getLotteryHistory&typ=json",
            "updateLotteryAddress": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=updateLotteryAddress&typ=json",
            "listsMarketing": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=listsMarketing&typ=json",
            "listsUserMarketing": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=listsUserMarketing&typ=json",
            "getMarketing": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=getMarketing&typ=json",
            "doMarketing": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=doMarketing&typ=json",
            "doCutPrice": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=doCutPrice&typ=json",
            "listsUserCutPriceHistory": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=listsUserCutPriceHistory&typ=json",
            "listsCutPriceActivity": "http://47.97.97.45/xiyou/index.php?ctl=Activity&met=listsCutPriceActivity&typ=json",
            "getCutPriceActivity": "http://47.97.97.45/xiyou/index.php?ctl=Activity&met=getCutPriceActivity&typ=json",
            "listsCutPriceHistory": "http://47.97.97.45/xiyou/index.php?ctl=Activity&met=listsCutPriceHistory&typ=json",
            "listsGroupbookingActivity": "http://47.97.97.45/xiyou/index.php?ctl=Activity&met=listsGroupbookingActivity&typ=json",
            "listsGroupbooking": "http://47.97.97.45/xiyou/index.php?ctl=Activity&met=listsGroupbooking&typ=json",
            "listsUserGroupbooking": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=listsUserGroupbooking&typ=json",
            "getUserGroupbooking": "http://47.97.97.45/xiyou/index.php?ctl=User_Activity&met=getUserGroupbooking&typ=json"
        },
        "pay": {
            "type": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=payType&typ=json",
            "lists": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=payLists&typ=json",
            "recharge": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=recharge&typ=json",
            "pay": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=pay&typ=json",
            "check_pay_passwd": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=checkPayPasswd&typ=json",
            "get_pay_passwd": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=getPayPasswd&typ=json",
            "asset": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=resourceIndex&typ=json",
            "consume_record": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=consumeRecord&typ=json",
            "get_consume_record": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=getConsumeRecord&typ=json",
            "consume_deposit": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=consumeDeposit&typ=json",
            "consume_trade": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=consumeTrade&typ=json",
            "consume_withdraw": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=consumeWithdraw&typ=json",
            "consume_withdraw_info": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=withdrawInfo&typ=json",
            "consume_withdraw_add": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=addWithdraw&typ=json",
            "addCard": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Card&met=addCard&typ=json",
            "cardHistory": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Card&met=cardHistory&typ=json",
            "reset_paypasswd": "http://47.97.97.45/xiyou/account.php?mdu=pay&ctl=Index&met=resetPayPassword&typ=json"
        },
        "fx": {
            "invite": "http://47.97.97.45/xiyou/index.php?ctl=Distribution_User&met=invite&typ=json",
            "lists": "http://47.97.97.45/xiyou/index.php?ctl=Distribution_User&met=lists&typ=json",
            "lists_commission": "http://47.97.97.45/xiyou/index.php?ctl=Distribution_User&met=listsCommission&typ=json",
            "lists_order": "http://47.97.97.45/xiyou/index.php?ctl=Distribution_User&met=listsOrder&typ=json",
            "index": "http://47.97.97.45/xiyou/index.php?ctl=Distribution_User&met=index&typ=json"
        }
    }

}